### PR TITLE
add mp3 files

### PR DESCRIPTION
**Pull request by cvn**
This is related to a PR in the main woscope repo. The demo needs these mp3 files for Safari compatibility.

transcoded at 320k from the ogg files:

``` sh
for i in *.ogg; do ffmpeg -i "$i" -b:a 320k "${i%ogg}mp3"; done;
```

### CODE REVIEW

**Comment by m1el** [comment]
IMO, it would be much better if the files were transcoded from lossless formats, if transcoded at all.

You can use lossless [oscillofun.flac](http://m1el.eu/woscope/woscope-music/oscillofun.flac) and [alpha_molecule.wav](https://github.com/D0ntPanic/soundscope/blob/master/alpha_molecule.wav)

Also [khrang.m4a](http://m1el.eu/woscope/woscope-music/khrang.m4a) (downloaded from https://www.youtube.com/watch?v=vAyCl4IHIz8) should be compatible with Safari.

Although I'd prefer to ask Jerobeam Fenderson for a lossless track for Khrậng :)

**Comment by cvn** [comment]
I updated this PR:
- I used the khrang.m4a file that you linked
- I transcoded a new mp3 from the oscillofun.flac file
-  alpha_molecule.mp3 is unchanged. I downloaded alpha_molecule.wav from your link, but Audition CC and ffmpeg couldn't read it. I tried twice. If you're able to get a clean copy, I could do the encode.

**Comment by Juesto** [comment]
Alpha Molecule needs text editing to make it work, you need to delete the contents of the first line until RIFF.
And Khrậng is free to download. in the video comments there's a direct link to the wav
here it is for convenience: http://space.jerobeamfenderson.net/download/khrang192khz.wav

**Comment by m1el** [comment]
@Juesto
- This pull request is closed, please open a new issue to request some changes or report an problem.
- All mp3 files work for me on all players I tried fb2k, mpv+ffmpeg, multiple browsers. Please provide the name of the browser or the player that's having problems playing the file.  Does the player support ID3v2 tags?  Are tags broken?
- "Text editing" out an ID3v2 tag is not the best way to fix binary files. There's surely a better way to remove an ID3v2 tag.
- At the time when this pull request was accepted, the wav file for khrang was not published yet.

**Comment by Juesto** [comment]
it's just that particular wav...., the original file refuses to play anywhere
i am not talking about mp3s

sorry for bothering

**Pull request merged**
